/**
 * Baccarat Analyzer V10.1
 * Path: tests/aiClosedLoopUIIntegration.test.js
 * Purpose: Full V10.1 Runtime and DOM-like UI integration test.
 */
import {CLOSED_LOOP_UI_STATE_VERSION,ClosedLoopUIState,ClosedLoopUIAction} from "../ui/closedloop/ClosedLoopUIState.js";
import ClosedLoopUIContext,{CLOSED_LOOP_UI_CONTEXT_VERSION} from "../ui/closedloop/ClosedLoopUIContext.js";
import ClosedLoopUIStore,{CLOSED_LOOP_UI_STORE_VERSION} from "../ui/closedloop/ClosedLoopUIStore.js";
import ClosedLoopResultMapper,{CLOSED_LOOP_RESULT_MAPPER_VERSION} from "../ui/closedloop/ClosedLoopResultMapper.js";
import ClosedLoopUIViewModel,{CLOSED_LOOP_UI_VIEW_MODEL_VERSION} from "../ui/closedloop/ClosedLoopUIViewModel.js";
import ClosedLoopUIRenderer,{CLOSED_LOOP_UI_RENDERER_VERSION} from "../ui/closedloop/ClosedLoopUIRenderer.js";
import ClosedLoopOutcomeCollector,{CLOSED_LOOP_OUTCOME_COLLECTOR_VERSION} from "../ui/closedloop/ClosedLoopOutcomeCollector.js";
import ClosedLoopUIController,{CLOSED_LOOP_UI_CONTROLLER_VERSION,ClosedLoopUIEvent} from "../ui/closedloop/ClosedLoopUIController.js";
import ClosedLoopUIEventBinder,{CLOSED_LOOP_UI_EVENT_BINDER_VERSION} from "../ui/closedloop/ClosedLoopUIEventBinder.js";
import ClosedLoopUIIntegration,{CLOSED_LOOP_UI_INTEGRATION_VERSION} from "../ui/closedloop/ClosedLoopUIIntegration.js";
import ClosedLoopUIRuntimeAdapter,{CLOSED_LOOP_UI_RUNTIME_ADAPTER_VERSION} from "../runtime/adapters/ClosedLoopUIRuntimeAdapter.js";
import {CLOSED_LOOP_UI_INTEGRATION_FACTORY_VERSION} from "../ui/closedloop/createClosedLoopUIIntegration.js";
const assert=(c,m)=>{if(!c)throw new Error(m);};
class FakeElement{constructor(){this.textContent="";this.disabled=false;this.listeners=new Map();}addEventListener(t,l){this.listeners.set(t,l);}removeEventListener(t,l){if(this.listeners.get(t)===l)this.listeners.delete(t);}async click(){return this.listeners.get("click")?.();}}
class FakeRoot{constructor(){this.elements=new Map();}querySelector(s){if(!this.elements.has(s))this.elements.set(s,new FakeElement());return this.elements.get(s);}}
export default async function aiClosedLoopUIIntegrationTest(){const messages=[];
 assert([CLOSED_LOOP_UI_STATE_VERSION,CLOSED_LOOP_UI_CONTEXT_VERSION,CLOSED_LOOP_UI_STORE_VERSION,CLOSED_LOOP_RESULT_MAPPER_VERSION,CLOSED_LOOP_UI_VIEW_MODEL_VERSION,CLOSED_LOOP_UI_RENDERER_VERSION,CLOSED_LOOP_OUTCOME_COLLECTOR_VERSION,CLOSED_LOOP_UI_CONTROLLER_VERSION,CLOSED_LOOP_UI_EVENT_BINDER_VERSION,CLOSED_LOOP_UI_INTEGRATION_VERSION,CLOSED_LOOP_UI_RUNTIME_ADAPTER_VERSION,CLOSED_LOOP_UI_INTEGRATION_FACTORY_VERSION].every(v=>v==="10.1.0"),"V10.1 version error");assert(ClosedLoopUIAction.ANALYZE==="analyze","action error");messages.push("✓ V10.1 AI Closed-Loop UI Integration 版本正確");
 const context=new ClosedLoopUIContext({observation:{round:{roundId:"r1"}},statistics:{roundCount:20},bankroll:{balance:1000}});assert(context.snapshot().bankroll.balance===1000,"context error");messages.push("✓ Closed Loop UI Context 正確");
 const store=new ClosedLoopUIStore();let n=0;store.subscribe(()=>n++);store.setState({status:"ready"});assert(n===1&&store.getSnapshot().status==="ready","store error");messages.push("✓ Closed Loop UI Store 正確");
 const mapper=new ClosedLoopResultMapper();const mapped=mapper.map({action:"continue",completedStages:["strategy"],outputs:{simulation:{merged:{probabilities:{Player:.4,Banker:.5,Tie:.1}}},prediction:{predictedOutcome:"Banker",confidence:.8},decision:{recommendation:{action:"bet",bestBet:"Banker",recommendedAmount:40}},strategy:{selection:{strategy:{strategyId:"balanced"}},plan:{betType:"Banker",amount:20}}}});assert(mapped.prediction==="Banker"&&mapped.confidence==="80%"&&mapped.strategy==="balanced","mapper error");messages.push("✓ Closed Loop Result Mapper 正確");
 const vm=new ClosedLoopUIViewModel({store:new ClosedLoopUIStore(),mapper});vm.setAnalyzing();assert(vm.snapshot.busy&&vm.snapshot.status==="analyzing","vm error");messages.push("✓ Closed Loop UI ViewModel 正確");
 const root=new FakeRoot();const renderer=new ClosedLoopUIRenderer({root});renderer.render({status:"ready",prediction:"Banker",busy:false,paused:false});assert(root.querySelector("[data-ai-status]").textContent==="ready"&&root.querySelector("[data-ai-prediction]").textContent==="Banker","renderer error");messages.push("✓ Closed Loop UI Renderer 正確");
 const outcome=new ClosedLoopOutcomeCollector().collect({winner:"Banker",profit:19});assert(outcome.profit===19,"outcome error");messages.push("✓ Closed Loop Outcome Collector 正確");
 const calls=[];const runtime={paused:false,destroyed:false,async cycle({context}){calls.push(context);const settled=!!context.actualOutcome;return {action:"continue",completedStages:settled?["simulation","prediction","decision","strategy","execution","feedback","learning","adaptive"]:["simulation","prediction","decision","strategy"],outputs:{simulation:{merged:{probabilities:{Player:.4,Banker:.5,Tie:.1}}},prediction:{predictedOutcome:"Banker",confidence:.8},decision:{recommendation:{action:"bet",bestBet:"Banker",recommendedAmount:40}},strategy:{selection:{strategy:{strategyId:"balanced"}},plan:{betType:"Banker",amount:20}},execution:settled?{monitoring:{accepted:true,status:"accepted"}}:null,feedback:settled?{action:"update"}:null,learning:settled?{reward:{reward:7}}:null,adaptive:settled?{snapshot:{revision:1}}:null}};},pause(){this.paused=true;},resume(){this.paused=false;},reset(){calls.length=0;},destroy(){this.destroyed=true;}};
 const cstore=new ClosedLoopUIStore(),cvm=new ClosedLoopUIViewModel({store:cstore,mapper}),events=[];const controller=new ClosedLoopUIController({runtime,viewModel:cvm,observationProvider:()=>({round:{roundId:"r1"}}),eventBus:{emit(type,payload){events.push({type,payload});}}});controller.connect();const a=await controller.runAnalysis({statistics:{roundCount:20}});assert(a.outputs.prediction.predictedOutcome==="Banker"&&controller.state===ClosedLoopUIState.AWAITING_RESULT,"analysis flow error");messages.push("✓ Connect → Analyze → Render 正確");
 const settled=await controller.submitRoundResult({winner:"Banker",profit:19});assert(settled.outputs.feedback.action==="update"&&cvm.snapshot.learning===7&&cvm.snapshot.adaptive==="revision 1","settlement flow error");messages.push("✓ Submit Result → Feedback → Learning → Adaptive → Render 正確");
 controller.pause();assert(controller.state===ClosedLoopUIState.PAUSED,"pause error");controller.resume();assert(controller.state===ClosedLoopUIState.READY,"resume error");messages.push("✓ Pause／Resume 正確");
 const broot=new FakeRoot(),brenderer=new ClosedLoopUIRenderer({root:broot});let ac=0,sc=0;const binder=new ClosedLoopUIEventBinder({controller:{async runAnalysis(){ac++;},async submitRoundResult(){sc++;},pause(){},resume(){},reset(){}},renderer:brenderer,outcomeProvider:()=>({winner:"Banker"})});binder.bind();await broot.querySelector("[data-ai-analyze]").click();await broot.querySelector("[data-ai-submit-result]").click();assert(ac===1&&sc===1&&binder.summary.bound,"binder error");messages.push("✓ Closed Loop UI Event Binder 正確");
 const istore=new ClosedLoopUIStore(),ivm=new ClosedLoopUIViewModel({store:istore,mapper}),iroot=new FakeRoot(),irenderer=new ClosedLoopUIRenderer({root:iroot}),ic=new ClosedLoopUIController({runtime,viewModel:ivm,observationProvider:()=>({round:{roundId:"r2"}})}),ib=new ClosedLoopUIEventBinder({controller:ic,renderer:irenderer,outcomeProvider:()=>({winner:"Banker",profit:19})}),integration=new ClosedLoopUIIntegration({store:istore,viewModel:ivm,renderer:irenderer,controller:ic,eventBinder:ib});integration.connect();const adapter=new ClosedLoopUIRuntimeAdapter({integration});assert(await adapter.runAnalysis({statistics:{roundCount:22}}),"adapter error");messages.push("✓ Closed Loop UI Integration 與 Runtime Adapter 正確");
 assert([ClosedLoopUIEvent.CONNECTED,ClosedLoopUIEvent.ANALYSIS_STARTED,ClosedLoopUIEvent.ANALYSIS_COMPLETED,ClosedLoopUIEvent.RESULT_SUBMITTED,ClosedLoopUIEvent.RESULT_COMPLETED,ClosedLoopUIEvent.RENDER_COMPLETED,ClosedLoopUIEvent.PAUSED,ClosedLoopUIEvent.RESUMED].every(t=>events.some(e=>e.type===t)),"events error");messages.push("✓ Closed Loop UI Events 正確");
 controller.reset();assert(controller.state===ClosedLoopUIState.IDLE&&!controller.summary.hasContext,"reset error");integration.destroy();assert(integration.summary.destroyed&&runtime.destroyed,"destroy error");messages.push("✓ Summary、Reset 與 Destroy 正確");
 return `\n${messages.join("\n")}\n\nAI Closed-Loop UI Integration V10.1 測試完成\n\nClosed Loop UI State：通過\nClosed Loop UI Context：通過\nClosed Loop UI Store：通過\nClosed Loop Result Mapper：通過\nClosed Loop UI ViewModel：通過\nClosed Loop UI Renderer：通過\nClosed Loop Outcome Collector：通過\nClosed Loop UI Controller：通過\nAnalysis Flow：通過\nSubmit Result Flow：通過\nPause／Resume：通過\nClosed Loop UI Event Binder：通過\nClosed Loop UI Integration：通過\nRuntime Adapter：通過\nEvents：通過\nLifecycle：通過\n`;}
