/** Baccarat Analyzer V7.1 */
import {LearningState,LearningAction} from "./LearningState.js";
import LearningMemory from "./LearningMemory.js";
import ExperienceBuffer from "./ExperienceBuffer.js";
import FeatureExtractor from "./FeatureExtractor.js";
import OutcomeEvaluator from "./OutcomeEvaluator.js";
import RewardCalculator from "./RewardCalculator.js";
import LearningPolicy from "./LearningPolicy.js";
export const LEARNING_ENGINE_VERSION="7.1.0";
export const LearningEvent=Object.freeze({STATE_CHANGE:"learning-engine:state-change",COLLECTING:"learning-engine:collecting",EXPERIENCE_CREATED:"learning-engine:experience-created",OUTCOME_EVALUATED:"learning-engine:outcome-evaluated",REWARD_CALCULATED:"learning-engine:reward-calculated",POLICY_APPLIED:"learning-engine:policy-applied",MEMORY_UPDATED:"learning-engine:memory-updated",COMPLETED:"learning-engine:completed",PAUSED:"learning-engine:paused",RESUMED:"learning-engine:resumed",ERROR:"learning-engine:error",DESTROYED:"learning-engine:destroyed"});
export default class LearningEngine {
  constructor({memory=null,buffer=null,featureExtractor=null,outcomeEvaluator=null,rewardCalculator=null,policy=null,eventBus=null,clock=()=>Date.now(),idFactory=null}={}){ if(eventBus!==null&&typeof eventBus.emit!=="function")throw new TypeError("eventBus requires emit()."); if(typeof clock!=="function")throw new TypeError("clock must be a function."); this.memory=memory??new LearningMemory(); this.buffer=buffer??new ExperienceBuffer(); this.featureExtractor=featureExtractor??new FeatureExtractor(); this.outcomeEvaluator=outcomeEvaluator??new OutcomeEvaluator(); this.rewardCalculator=rewardCalculator??new RewardCalculator(); this.policy=policy??new LearningPolicy(); this.eventBus=eventBus; this.clock=clock; this.sequence=0; this.idFactory=idFactory??(({sequence,timestamp})=>`experience-${timestamp}-${sequence}`); this.state=LearningState.IDLE; this.previousState=null; this.paused=false; this.lastExperience=null; this.lastError=null; this.learningCount=0; this.destroyed=false; }
  emit(type,payload=null){ return this.eventBus?.emit(type,payload,{source:"learning-engine"})??null; }
  setState(state){ const previous=this.state; this.previousState=previous; this.state=state; this.emit(LearningEvent.STATE_CHANGE,{previous,current:state}); return this; }
  assertNotDestroyed(){ if(this.destroyed)throw new Error("LearningEngine has been destroyed."); }
  async learn({decision,outcome,analysis={},statistics={},roadmap={},bankroll={},before={},after={},metadata={}}={}){ this.assertNotDestroyed(); if(this.paused)return null; if(!decision)throw new TypeError("LearningEngine requires decision."); this.setState(LearningState.COLLECTING); this.emit(LearningEvent.COLLECTING,{decision,outcome}); try{ this.sequence++; const timestamp=this.clock(); const experienceId=this.idFactory({sequence:this.sequence,timestamp}); const features=await this.featureExtractor.extract({decision,analysis,statistics,roadmap,bankroll}); this.emit(LearningEvent.EXPERIENCE_CREATED,{experienceId,features}); this.setState(LearningState.EVALUATING); const evaluation=await this.outcomeEvaluator.evaluate({decision,outcome,before,after}); this.emit(LearningEvent.OUTCOME_EVALUATED,evaluation); const rewardResult=await this.rewardCalculator.calculate({evaluation,features}); this.emit(LearningEvent.REWARD_CALCULATED,rewardResult); this.setState(LearningState.LEARNING); const base={version:LEARNING_ENGINE_VERSION,experienceId,decisionId:decision.decisionId??null,timestamp,state:features,action:decision.action??null,reward:rewardResult.reward,nextState:{outcome,after},evaluation,rewardReasons:rewardResult.reasons,weight:1,metadata:{...metadata}}; const policyDecision=await this.policy.decide({reward:rewardResult.reward,experience:base}); this.emit(LearningEvent.POLICY_APPLIED,policyDecision); const experience={...base,policy:policyDecision,weight:policyDecision.weight}; this.buffer.push(experience); if(policyDecision.action===LearningAction.FORGET)this.memory.remove(experienceId); else this.memory.add(experience); this.lastExperience=experience; this.learningCount++; this.emit(LearningEvent.MEMORY_UPDATED,{experience,memory:this.memory.summary}); this.setState(LearningState.COMPLETED); this.emit(LearningEvent.COMPLETED,experience); return experience; }catch(error){ return this.handleError(error,"learn"); } }
  sample(size=1){ this.assertNotDestroyed(); return this.buffer.sample(size); }
  pause(){ this.assertNotDestroyed(); this.paused=true; this.setState(LearningState.PAUSED); this.emit(LearningEvent.PAUSED,this.summary); return this.summary; }
  resume(){ this.assertNotDestroyed(); this.paused=false; this.setState(LearningState.IDLE); this.emit(LearningEvent.RESUMED,this.summary); return this.summary; }
  reset(){ this.assertNotDestroyed(); this.memory.clear(); this.buffer.clear(); this.lastExperience=null; this.lastError=null; this.learningCount=0; this.paused=false; this.setState(LearningState.IDLE); return this; }
  handleError(error,phase){ this.lastError=error; this.setState(LearningState.ERROR); this.emit(LearningEvent.ERROR,{phase,message:error?.message??String(error)}); throw error; }
  destroy(){ if(this.destroyed)return this; this.memory.clear(); this.buffer.clear(); this.lastExperience=null; this.lastError=null; this.destroyed=true; this.setState(LearningState.DESTROYED); this.emit(LearningEvent.DESTROYED,null); return this; }
  get summary(){ return {version:LEARNING_ENGINE_VERSION,state:this.state,previousState:this.previousState,destroyed:this.destroyed,paused:this.paused,learningCount:this.learningCount,hasExperience:Boolean(this.lastExperience),lastError:this.lastError?.message??null,memory:this.memory.summary,buffer:this.buffer.summary,components:{featureExtractor:this.featureExtractor.summary,outcomeEvaluator:this.outcomeEvaluator.summary,rewardCalculator:this.rewardCalculator.summary,policy:this.policy.summary}}; }
}
