/**
 * Baccarat Analyzer V10.1
 * Path: ui/closedloop/ClosedLoopUIController.js
 * Purpose: Coordinates Dashboard analysis and outcome submission with Closed-Loop Runtime.
 */
import {ClosedLoopUIState} from "./ClosedLoopUIState.js";
import ClosedLoopUIContext from "./ClosedLoopUIContext.js";
import ClosedLoopOutcomeCollector from "./ClosedLoopOutcomeCollector.js";
export const CLOSED_LOOP_UI_CONTROLLER_VERSION="10.1.0";
export const ClosedLoopUIEvent=Object.freeze({STATE_CHANGE:"ai-closed-loop-ui:state-change",CONNECTED:"ai-closed-loop-ui:connected",ANALYSIS_STARTED:"ai-closed-loop-ui:analysis-started",ANALYSIS_COMPLETED:"ai-closed-loop-ui:analysis-completed",RESULT_SUBMITTED:"ai-closed-loop-ui:result-submitted",RESULT_COMPLETED:"ai-closed-loop-ui:result-completed",RENDER_COMPLETED:"ai-closed-loop-ui:render-completed",PAUSED:"ai-closed-loop-ui:paused",RESUMED:"ai-closed-loop-ui:resumed",RESET:"ai-closed-loop-ui:reset",ERROR:"ai-closed-loop-ui:error",DESTROYED:"ai-closed-loop-ui:destroyed"});
export default class ClosedLoopUIController{
 constructor({runtime,viewModel,outcomeCollector=null,observationProvider=null,eventBus=null}={}){if(!runtime?.cycle)throw new TypeError("runtime.cycle required");if(!viewModel?.applyResult)throw new TypeError("viewModel required");this.runtime=runtime;this.viewModel=viewModel;this.outcomeCollector=outcomeCollector??new ClosedLoopOutcomeCollector();this.observationProvider=observationProvider??(()=>({}));this.eventBus=eventBus;this.state=ClosedLoopUIState.IDLE;this.previousState=null;this.connected=false;this.paused=false;this.destroyed=false;this.lastContext=null;this.lastResult=null;this.lastError=null;}
 emit(type,payload=null){return this.eventBus?.emit(type,payload,{source:"ai-closed-loop-ui"})??null;}
 setState(state){const previous=this.state;this.previousState=previous;this.state=state;this.emit(ClosedLoopUIEvent.STATE_CHANGE,{previous,current:state});return this;}
 assertNotDestroyed(){if(this.destroyed)throw new Error("ClosedLoopUIController destroyed");}
 connect(){this.assertNotDestroyed();this.setState(ClosedLoopUIState.CONNECTING);this.viewModel.setConnecting();this.connected=true;this.setState(ClosedLoopUIState.READY);this.viewModel.setReady();this.emit(ClosedLoopUIEvent.CONNECTED,this.summary);return this.summary;}
 async runAnalysis({observation=null,statistics=null,roadmap=null,bankroll=null,settings=null,metadata={}}={}){this.assertNotDestroyed();if(!this.connected)this.connect();if(this.paused)return null;this.setState(ClosedLoopUIState.ANALYZING);this.viewModel.setAnalyzing();this.emit(ClosedLoopUIEvent.ANALYSIS_STARTED,null);try{const context=new ClosedLoopUIContext({observation:observation??this.observationProvider(),statistics,roadmap,bankroll,settings,metadata});this.lastContext=context;const result=await this.runtime.cycle({context:{observation:context.observation,statistics,roadmap,bankroll,settings,metadata}});this.lastResult=result;this.viewModel.applyResult(result);this.setState(ClosedLoopUIState.AWAITING_RESULT);this.viewModel.setAwaitingResult();this.emit(ClosedLoopUIEvent.ANALYSIS_COMPLETED,result);this.emit(ClosedLoopUIEvent.RENDER_COMPLETED,this.viewModel.snapshot);return result;}catch(error){return this.handleError(error,"runAnalysis");}}
 async submitRoundResult(input={}){this.assertNotDestroyed();if(this.paused)return null;if(!this.lastContext)throw new Error("No analysis context is available.");this.setState(ClosedLoopUIState.SUBMITTING_RESULT);this.viewModel.setSubmittingResult();try{const actualOutcome=this.outcomeCollector.collect(input);this.emit(ClosedLoopUIEvent.RESULT_SUBMITTED,actualOutcome);const c=this.lastContext.snapshot();const result=await this.runtime.cycle({context:{observation:c.observation,actualOutcome,statistics:c.statistics,roadmap:c.roadmap,bankroll:c.bankroll,settings:c.settings,metadata:c.metadata}});this.lastResult=result;this.viewModel.applyResult(result);this.setState(ClosedLoopUIState.COMPLETED);this.emit(ClosedLoopUIEvent.RESULT_COMPLETED,result);this.emit(ClosedLoopUIEvent.RENDER_COMPLETED,this.viewModel.snapshot);return result;}catch(error){return this.handleError(error,"submitRoundResult");}}
 pause(){this.assertNotDestroyed();this.runtime.pause();this.paused=true;this.setState(ClosedLoopUIState.PAUSED);this.viewModel.setPaused(true);this.emit(ClosedLoopUIEvent.PAUSED,this.summary);return this.summary;}
 resume(){this.assertNotDestroyed();this.runtime.resume();this.paused=false;this.setState(ClosedLoopUIState.READY);this.viewModel.setPaused(false);this.emit(ClosedLoopUIEvent.RESUMED,this.summary);return this.summary;}
 reset(){this.assertNotDestroyed();this.runtime.reset();this.lastContext=null;this.lastResult=null;this.lastError=null;this.paused=false;this.connected=false;this.viewModel.reset();this.setState(ClosedLoopUIState.IDLE);this.emit(ClosedLoopUIEvent.RESET,this.summary);return this;}
 handleError(error,phase){this.lastError=error;this.setState(ClosedLoopUIState.ERROR);this.viewModel.applyError(error);this.emit(ClosedLoopUIEvent.ERROR,{phase,message:error?.message??String(error)});throw error;}
 destroy(){if(this.destroyed)return this;this.runtime.destroy();this.lastContext=null;this.lastResult=null;this.destroyed=true;this.connected=false;this.setState(ClosedLoopUIState.DESTROYED);this.emit(ClosedLoopUIEvent.DESTROYED,null);return this;}
 get summary(){return {version:CLOSED_LOOP_UI_CONTROLLER_VERSION,state:this.state,previousState:this.previousState,connected:this.connected,paused:this.paused,destroyed:this.destroyed,hasContext:!!this.lastContext,hasResult:!!this.lastResult,lastError:this.lastError?.message??null,view:this.viewModel.snapshot};}
}
